version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=grocery_store

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=grocery_store
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./public/frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  mysql_data: 